
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T06:17:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "061721b1d52237f604df74dd7f42f7694bfb4bf9",
 "version": "0.7.0.post.dev86"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
