# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedlearner/common/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fedlearner/common/common.proto',
  package='fedlearner.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x66\x65\x64learner/common/common.proto\x12\x11\x66\x65\x64learner.common\"L\n\x06Status\x12+\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1d.fedlearner.common.StatusCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"{\n\x0e\x44\x61taSourceMeta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rpartition_num\x18\x02 \x01(\r\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\x12\x1e\n\x16negative_sampling_rate\x18\x05 \x01(\x02\"\xd8\x01\n\nDataSource\x12;\n\x10\x64\x61ta_source_meta\x18\x01 \x01(\x0b\x32!.fedlearner.common.DataSourceMeta\x12\x17\n\x0foutput_base_dir\x18\x02 \x01(\t\x12\'\n\x04role\x18\x03 \x01(\x0e\x32\x19.fedlearner.common.FLRole\x12\x31\n\x05state\x18\x04 \x01(\x0e\x32\".fedlearner.common.DataSourceState\x12\x18\n\x10raw_data_sub_dir\x18\x05 \x01(\t*\x8b\x02\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x18\n\x14STATUS_UNKNOWN_ERROR\x10\x01\x12\x1a\n\x16STATUS_INVALID_REQUEST\x10\x02\x12\x17\n\x13STATUS_NO_MORE_DATA\x10\x03\x12\x18\n\x14STATUS_DATA_FINISHED\x10\x04\x12\x1d\n\x19STATUS_MESSAGE_DUPLICATED\x10\x05\x12\x1a\n\x16STATUS_MESSAGE_MISSING\x10\x06\x12\x1d\n\x19STATUS_INVALID_DATA_BLOCK\x10\x07\x12&\n\"STATUS_WAIT_FOR_SYNCING_CHECKPOINT\x10\x08*\"\n\x06\x46LRole\x12\n\n\x06Leader\x10\x00\x12\x0c\n\x08\x46ollower\x10\x01*]\n\x0f\x44\x61taSourceState\x12\x0b\n\x07UnKnown\x10\x00\x12\x08\n\x04Init\x10\x01\x12\x0e\n\nProcessing\x10\x02\x12\t\n\x05Ready\x10\x03\x12\x0c\n\x08\x46inished\x10\x04\x12\n\n\x06\x46\x61iled\x10\x05\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='fedlearner.common.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNKNOWN_ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NO_MORE_DATA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_DATA_FINISHED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_MESSAGE_DUPLICATED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_MESSAGE_MISSING', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_DATA_BLOCK', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_WAIT_FOR_SYNCING_CHECKPOINT', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=476,
  serialized_end=743,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_FLROLE = _descriptor.EnumDescriptor(
  name='FLRole',
  full_name='fedlearner.common.FLRole',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Leader', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Follower', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=745,
  serialized_end=779,
)
_sym_db.RegisterEnumDescriptor(_FLROLE)

FLRole = enum_type_wrapper.EnumTypeWrapper(_FLROLE)
_DATASOURCESTATE = _descriptor.EnumDescriptor(
  name='DataSourceState',
  full_name='fedlearner.common.DataSourceState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnKnown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Init', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Processing', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Ready', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Finished', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=781,
  serialized_end=874,
)
_sym_db.RegisterEnumDescriptor(_DATASOURCESTATE)

DataSourceState = enum_type_wrapper.EnumTypeWrapper(_DATASOURCESTATE)
STATUS_SUCCESS = 0
STATUS_UNKNOWN_ERROR = 1
STATUS_INVALID_REQUEST = 2
STATUS_NO_MORE_DATA = 3
STATUS_DATA_FINISHED = 4
STATUS_MESSAGE_DUPLICATED = 5
STATUS_MESSAGE_MISSING = 6
STATUS_INVALID_DATA_BLOCK = 7
STATUS_WAIT_FOR_SYNCING_CHECKPOINT = 8
Leader = 0
Follower = 1
UnKnown = 0
Init = 1
Processing = 2
Ready = 3
Finished = 4
Failed = 5



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='fedlearner.common.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='fedlearner.common.Status.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='fedlearner.common.Status.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=129,
)


_DATASOURCEMETA = _descriptor.Descriptor(
  name='DataSourceMeta',
  full_name='fedlearner.common.DataSourceMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fedlearner.common.DataSourceMeta.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition_num', full_name='fedlearner.common.DataSourceMeta.partition_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='fedlearner.common.DataSourceMeta.start_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='fedlearner.common.DataSourceMeta.end_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='negative_sampling_rate', full_name='fedlearner.common.DataSourceMeta.negative_sampling_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=254,
)


_DATASOURCE = _descriptor.Descriptor(
  name='DataSource',
  full_name='fedlearner.common.DataSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_source_meta', full_name='fedlearner.common.DataSource.data_source_meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_base_dir', full_name='fedlearner.common.DataSource.output_base_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='fedlearner.common.DataSource.role', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='fedlearner.common.DataSource.state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_data_sub_dir', full_name='fedlearner.common.DataSource.raw_data_sub_dir', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=473,
)

_STATUS.fields_by_name['code'].enum_type = _STATUSCODE
_DATASOURCE.fields_by_name['data_source_meta'].message_type = _DATASOURCEMETA
_DATASOURCE.fields_by_name['role'].enum_type = _FLROLE
_DATASOURCE.fields_by_name['state'].enum_type = _DATASOURCESTATE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['DataSourceMeta'] = _DATASOURCEMETA
DESCRIPTOR.message_types_by_name['DataSource'] = _DATASOURCE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['FLRole'] = _FLROLE
DESCRIPTOR.enum_types_by_name['DataSourceState'] = _DATASOURCESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'fedlearner.common.common_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.Status)
  })
_sym_db.RegisterMessage(Status)

DataSourceMeta = _reflection.GeneratedProtocolMessageType('DataSourceMeta', (_message.Message,), {
  'DESCRIPTOR' : _DATASOURCEMETA,
  '__module__' : 'fedlearner.common.common_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataSourceMeta)
  })
_sym_db.RegisterMessage(DataSourceMeta)

DataSource = _reflection.GeneratedProtocolMessageType('DataSource', (_message.Message,), {
  'DESCRIPTOR' : _DATASOURCE,
  '__module__' : 'fedlearner.common.common_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataSource)
  })
_sym_db.RegisterMessage(DataSource)


# @@protoc_insertion_point(module_scope)
