# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedlearner/common/scheduler_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fedlearner.common import common_pb2 as fedlearner_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fedlearner/common/scheduler_service.proto',
  package='fedlearner.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)fedlearner/common/scheduler_service.proto\x12\x11\x66\x65\x64learner.common\x1a\x1e\x66\x65\x64learner/common/common.proto\"`\n\x10ModelAuthRequest\x12\x11\n\tmodel_uri\x18\x01 \x01(\t\x12\x10\n\x08\x63ode_url\x18\x02 \x01(\t\x12\x11\n\timage_uri\x18\x03 \x01(\t\x12\x14\n\x0cmodel_commit\x18\x04 \x01(\t\"J\n\x08\x44\x61taMeta\x12\x18\n\x10\x64\x61ta_source_name\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\"\xd0\x01\n\x0fTrainJobRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x02 \x01(\t\x12\x11\n\tmodel_uri\x18\x03 \x01(\t\x12\x14\n\x0cmodel_commit\x18\x04 \x01(\t\x12\x17\n\x0fserving_version\x18\x05 \x01(\t\x12\x10\n\x08pair_num\x18\x06 \x01(\x05\x12.\n\tdata_meta\x18\x07 \x01(\x0b\x32\x1b.fedlearner.common.DataMeta\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\"\xcf\x01\n\x0e\x45valJobRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x02 \x01(\t\x12\x11\n\tmodel_uri\x18\x03 \x01(\t\x12\x14\n\x0cmodel_commit\x18\x04 \x01(\t\x12\x17\n\x0fserving_version\x18\x05 \x01(\t\x12\x10\n\x08pair_num\x18\x06 \x01(\x05\x12.\n\tdata_meta\x18\x07 \x01(\x0b\x32\x1b.fedlearner.common.DataMeta\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t2\xf8\x01\n\tScheduler\x12K\n\tModelAuth\x12#.fedlearner.common.ModelAuthRequest\x1a\x19.fedlearner.common.Status\x12O\n\x0eSubmitTrainJob\x12\".fedlearner.common.TrainJobRequest\x1a\x19.fedlearner.common.Status\x12M\n\rSubmitEvalJob\x12!.fedlearner.common.EvalJobRequest\x1a\x19.fedlearner.common.Statusb\x06proto3'
  ,
  dependencies=[fedlearner_dot_common_dot_common__pb2.DESCRIPTOR,])




_MODELAUTHREQUEST = _descriptor.Descriptor(
  name='ModelAuthRequest',
  full_name='fedlearner.common.ModelAuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_uri', full_name='fedlearner.common.ModelAuthRequest.model_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code_url', full_name='fedlearner.common.ModelAuthRequest.code_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_uri', full_name='fedlearner.common.ModelAuthRequest.image_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_commit', full_name='fedlearner.common.ModelAuthRequest.model_commit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=192,
)


_DATAMETA = _descriptor.Descriptor(
  name='DataMeta',
  full_name='fedlearner.common.DataMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_source_name', full_name='fedlearner.common.DataMeta.data_source_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='fedlearner.common.DataMeta.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='fedlearner.common.DataMeta.end_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=268,
)


_TRAINJOBREQUEST = _descriptor.Descriptor(
  name='TrainJobRequest',
  full_name='fedlearner.common.TrainJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fedlearner.common.TrainJobRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_id', full_name='fedlearner.common.TrainJobRequest.application_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_uri', full_name='fedlearner.common.TrainJobRequest.model_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_commit', full_name='fedlearner.common.TrainJobRequest.model_commit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serving_version', full_name='fedlearner.common.TrainJobRequest.serving_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair_num', full_name='fedlearner.common.TrainJobRequest.pair_num', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_meta', full_name='fedlearner.common.TrainJobRequest.data_meta', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='fedlearner.common.TrainJobRequest.description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=479,
)


_EVALJOBREQUEST = _descriptor.Descriptor(
  name='EvalJobRequest',
  full_name='fedlearner.common.EvalJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fedlearner.common.EvalJobRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_id', full_name='fedlearner.common.EvalJobRequest.application_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_uri', full_name='fedlearner.common.EvalJobRequest.model_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_commit', full_name='fedlearner.common.EvalJobRequest.model_commit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serving_version', full_name='fedlearner.common.EvalJobRequest.serving_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair_num', full_name='fedlearner.common.EvalJobRequest.pair_num', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_meta', full_name='fedlearner.common.EvalJobRequest.data_meta', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='fedlearner.common.EvalJobRequest.description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=689,
)

_TRAINJOBREQUEST.fields_by_name['data_meta'].message_type = _DATAMETA
_EVALJOBREQUEST.fields_by_name['data_meta'].message_type = _DATAMETA
DESCRIPTOR.message_types_by_name['ModelAuthRequest'] = _MODELAUTHREQUEST
DESCRIPTOR.message_types_by_name['DataMeta'] = _DATAMETA
DESCRIPTOR.message_types_by_name['TrainJobRequest'] = _TRAINJOBREQUEST
DESCRIPTOR.message_types_by_name['EvalJobRequest'] = _EVALJOBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelAuthRequest = _reflection.GeneratedProtocolMessageType('ModelAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELAUTHREQUEST,
  '__module__' : 'fedlearner.common.scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.ModelAuthRequest)
  })
_sym_db.RegisterMessage(ModelAuthRequest)

DataMeta = _reflection.GeneratedProtocolMessageType('DataMeta', (_message.Message,), {
  'DESCRIPTOR' : _DATAMETA,
  '__module__' : 'fedlearner.common.scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.DataMeta)
  })
_sym_db.RegisterMessage(DataMeta)

TrainJobRequest = _reflection.GeneratedProtocolMessageType('TrainJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINJOBREQUEST,
  '__module__' : 'fedlearner.common.scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.TrainJobRequest)
  })
_sym_db.RegisterMessage(TrainJobRequest)

EvalJobRequest = _reflection.GeneratedProtocolMessageType('EvalJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALJOBREQUEST,
  '__module__' : 'fedlearner.common.scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:fedlearner.common.EvalJobRequest)
  })
_sym_db.RegisterMessage(EvalJobRequest)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='fedlearner.common.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=692,
  serialized_end=940,
  methods=[
  _descriptor.MethodDescriptor(
    name='ModelAuth',
    full_name='fedlearner.common.Scheduler.ModelAuth',
    index=0,
    containing_service=None,
    input_type=_MODELAUTHREQUEST,
    output_type=fedlearner_dot_common_dot_common__pb2._STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitTrainJob',
    full_name='fedlearner.common.Scheduler.SubmitTrainJob',
    index=1,
    containing_service=None,
    input_type=_TRAINJOBREQUEST,
    output_type=fedlearner_dot_common_dot_common__pb2._STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitEvalJob',
    full_name='fedlearner.common.Scheduler.SubmitEvalJob',
    index=2,
    containing_service=None,
    input_type=_EVALJOBREQUEST,
    output_type=fedlearner_dot_common_dot_common__pb2._STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
