# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fedlearner.common import trainer_master_service_pb2 as fedlearner_dot_common_dot_trainer__master__service__pb2


class TrainerMasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestDataBlock = channel.unary_unary(
                '/fedlearner.common.TrainerMasterService/RequestDataBlock',
                request_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockRequest.SerializeToString,
                response_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockResponse.FromString,
                )
        self.GetDataBlockCheckpoint = channel.unary_unary(
                '/fedlearner.common.TrainerMasterService/GetDataBlockCheckpoint',
                request_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointRequest.SerializeToString,
                response_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointResponse.FromString,
                )
        self.RestoreDataBlockCheckpoint = channel.unary_unary(
                '/fedlearner.common.TrainerMasterService/RestoreDataBlockCheckpoint',
                request_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointRequest.SerializeToString,
                response_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointResponse.FromString,
                )


class TrainerMasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestDataBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataBlockCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreDataBlockCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerMasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestDataBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDataBlock,
                    request_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockRequest.FromString,
                    response_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockResponse.SerializeToString,
            ),
            'GetDataBlockCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataBlockCheckpoint,
                    request_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointRequest.FromString,
                    response_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointResponse.SerializeToString,
            ),
            'RestoreDataBlockCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreDataBlockCheckpoint,
                    request_deserializer=fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointRequest.FromString,
                    response_serializer=fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedlearner.common.TrainerMasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainerMasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestDataBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedlearner.common.TrainerMasterService/RequestDataBlock',
            fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockRequest.SerializeToString,
            fedlearner_dot_common_dot_trainer__master__service__pb2.DataBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataBlockCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedlearner.common.TrainerMasterService/GetDataBlockCheckpoint',
            fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointRequest.SerializeToString,
            fedlearner_dot_common_dot_trainer__master__service__pb2.GetDataBlockCheckpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreDataBlockCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedlearner.common.TrainerMasterService/RestoreDataBlockCheckpoint',
            fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointRequest.SerializeToString,
            fedlearner_dot_common_dot_trainer__master__service__pb2.RestoreDataBlockCheckpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
