[tool.poetry]
name = "hashicorp-vault-client-api"
version = "0.3.2"
description = "HashiCorp Vault Client API"
authors = ["Jerod Gawne <jerodgawne@gmail.com>"]

[tool.poetry.dependencies]
base-client-api = "^2.2.2"
python = "^3.8.0"  # Recommended 3.9+

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
