[tool.poetry]
name = "sdsort"
version = "0.1.1"
description = "Sorts class methods according to the step-down rule"
authors = ["Eiríkur Fannar Torfason <eirikur.torfason@gmail.com>"]

readme = "README.md"
repository = "https://github.com/eirikurt/sdsort"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^20.8b1"
mypy = "^0.812"
flake8 = "^3.9.1"
isort = "^5.8.0"

[tool.poetry.scripts]
sdsort = "sdsort:main"

[tool.black]
line-length = 115
target-version = ['py37']

[tool.isort]
line_length = 115
profile = "black"
known_local_folder = ["test"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
