# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yPLnQZ_NZc35_l4QFzW4QOs11ybuKjkH
"""

def coolprint():
    print("This is UAMERICA! :)")

def myaddition(x,y):
    return x + y