
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-03T10:29:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "43c946f292015205af6231cf1b9dfd9da3176a88",
 "version": "0.0.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
