#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['vvvvid_downloader']

package_data = \
{'': ['*']}

install_requires = \
['inquirer ==2.7.0',
 'httpx ==0.18.1',
 'typer ==0.3.2',
 'tqdm ==4.60.0',
 'colorama ==0.4.4']

setup(name='vvvvid_downloader',
      version='1.2.0',
      description='Uno script in Python per scaricare, in modo semplice, gli anime anime da VVVVID. ',
      author='Nearata',
      author_email='williamdicicco@protonmail.com',
      url='https://github.com/nearata/vvvvid-downloader',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.9',
     )
