
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-06T12:38:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe6a0b3eb489292ea51ef4c7ed9bb74c748c8efe",
 "version": "4.5.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
