[tool.poetry]
name = "dropbox_api_team_3"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
dropbox = "^11.7.0"
python-dotenv = "^0.17.1"
pytest-mock = "^3.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.scripts]
dropbox_api_team_3 = "dropbox_api_team_3.main:main"
