
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-30T12:49:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0ea82af24c8ac4e659d6e440bf5ee8fc99e3d4c",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
