[tool.poetry]
name = "af-ibov-parser"
version = "0.1.0"
description = "fillme"
authors = ["Leonardo Rossetti <me@lrossetti.com>"]
license = "MIT"
packages = [
  { include = "af_ibov_parser", from = "src" }
]
readme = "README.md"

[tool.poetry.scripts]
af-ibov-parser = 'af_ibov_parser.cli:main'

[tool.poetry.dependencies]
python = "^3.9"
canonicaljson = "^1.4.0"

[tool.poetry.dev-dependencies]
Sphinx = "^3.5.4"
sphinx-rtd-theme = "^0.5.2"
mypy = "^0.812"
pytest = "^6.2.3"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }
