
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T03:42:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a6f8ed7f0f4057bdbb8321b3e246dae50b25647",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
