[tool.poetry]
name = "motor-bundle"
version = "2.0.0"
description = ""
authors = ["Alvaro Garcia <maxpowel@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6,<4.0.0"
applauncher = "^2.0.0"
motor = "^2.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
