# Generated by Django 2.2.15 on 2020-08-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0006_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='uid',
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firebase.User'),
            preserve_default=False,
        ),
    ]
