[tool.poetry]
name = "lime-etl"
version = "0.1.29"
description = "Simple ETL job runner"
authors = ["Mark Stefanovic"]
include = ["lime_etl/py.typed"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
sqlalchemy = ">=1.3.19,<2.0"
lime-uow = ">=0.1.46"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.2"
mypy = ">=0.79"
sqlalchemy-stubs = ">=0.3,<1.0"
psycopg2-binary = ">=2.8.6,<2.9"
python-dotenv = ">=0.15.0,<1.0"
psycopg2 = ">=2.8.6,<3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
