
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T11:43:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f508e7ce1af04b28d0dc65a6c2f0a775ae3a6f9b",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
