# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from edge_impulse_sdk.configuration import Configuration


class OrganizationGetCreateProjectsResponseAllOfJobs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'organization_id': 'int',
        'name': 'str',
        'upload_type': 'str',
        'transform_job_status': 'str',
        'upload_job_id': 'int',
        'upload_job_status': 'str',
        'project_owner': 'str',
        'project_id': 'int',
        'project_name': 'str',
        'transformation_block_id': 'int',
        'transformation_block_name': 'str',
        'created': 'datetime',
        'output_dataset_name': 'str',
        'total_download_file_count': 'int',
        'total_download_file_size': 'int',
        'total_download_file_size_string': 'str',
        'total_upload_file_count': 'int'
    }

    attribute_map = {
        'id': 'id',
        'organization_id': 'organizationId',
        'name': 'name',
        'upload_type': 'uploadType',
        'transform_job_status': 'transformJobStatus',
        'upload_job_id': 'uploadJobId',
        'upload_job_status': 'uploadJobStatus',
        'project_owner': 'projectOwner',
        'project_id': 'projectId',
        'project_name': 'projectName',
        'transformation_block_id': 'transformationBlockId',
        'transformation_block_name': 'transformationBlockName',
        'created': 'created',
        'output_dataset_name': 'outputDatasetName',
        'total_download_file_count': 'totalDownloadFileCount',
        'total_download_file_size': 'totalDownloadFileSize',
        'total_download_file_size_string': 'totalDownloadFileSizeString',
        'total_upload_file_count': 'totalUploadFileCount'
    }

    def __init__(self, id=None, organization_id=None, name=None, upload_type=None, transform_job_status=None, upload_job_id=None, upload_job_status=None, project_owner=None, project_id=None, project_name=None, transformation_block_id=None, transformation_block_name=None, created=None, output_dataset_name=None, total_download_file_count=None, total_download_file_size=None, total_download_file_size_string=None, total_upload_file_count=None, local_vars_configuration=None):  # noqa: E501
        """OrganizationGetCreateProjectsResponseAllOfJobs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._organization_id = None
        self._name = None
        self._upload_type = None
        self._transform_job_status = None
        self._upload_job_id = None
        self._upload_job_status = None
        self._project_owner = None
        self._project_id = None
        self._project_name = None
        self._transformation_block_id = None
        self._transformation_block_name = None
        self._created = None
        self._output_dataset_name = None
        self._total_download_file_count = None
        self._total_download_file_size = None
        self._total_download_file_size_string = None
        self._total_upload_file_count = None
        self.discriminator = None

        self.id = id
        if organization_id is not None:
            self.organization_id = organization_id
        self.name = name
        self.upload_type = upload_type
        self.transform_job_status = transform_job_status
        if upload_job_id is not None:
            self.upload_job_id = upload_job_id
        self.upload_job_status = upload_job_status
        if project_owner is not None:
            self.project_owner = project_owner
        if project_id is not None:
            self.project_id = project_id
        if project_name is not None:
            self.project_name = project_name
        if transformation_block_id is not None:
            self.transformation_block_id = transformation_block_id
        if transformation_block_name is not None:
            self.transformation_block_name = transformation_block_name
        self.created = created
        if output_dataset_name is not None:
            self.output_dataset_name = output_dataset_name
        self.total_download_file_count = total_download_file_count
        self.total_download_file_size = total_download_file_size
        self.total_download_file_size_string = total_download_file_size_string
        if total_upload_file_count is not None:
            self.total_upload_file_count = total_upload_file_count

    @property
    def id(self):
        """Gets the id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param id: The id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def organization_id(self):
        """Gets the organization_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The organization_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param organization_id: The organization_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """

        self._organization_id = organization_id

    @property
    def name(self):
        """Gets the name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param name: The name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def upload_type(self):
        """Gets the upload_type of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The upload_type of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._upload_type

    @upload_type.setter
    def upload_type(self, upload_type):
        """Sets the upload_type of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param upload_type: The upload_type of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and upload_type is None:  # noqa: E501
            raise ValueError("Invalid value for `upload_type`, must not be `None`")  # noqa: E501
        allowed_values = ["dataset", "project"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and upload_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `upload_type` ({0}), must be one of {1}"  # noqa: E501
                .format(upload_type, allowed_values)
            )

        self._upload_type = upload_type

    @property
    def transform_job_status(self):
        """Gets the transform_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The transform_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._transform_job_status

    @transform_job_status.setter
    def transform_job_status(self, transform_job_status):
        """Sets the transform_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param transform_job_status: The transform_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and transform_job_status is None:  # noqa: E501
            raise ValueError("Invalid value for `transform_job_status`, must not be `None`")  # noqa: E501
        allowed_values = ["waiting", "created", "started", "finished", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and transform_job_status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `transform_job_status` ({0}), must be one of {1}"  # noqa: E501
                .format(transform_job_status, allowed_values)
            )

        self._transform_job_status = transform_job_status

    @property
    def upload_job_id(self):
        """Gets the upload_job_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The upload_job_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._upload_job_id

    @upload_job_id.setter
    def upload_job_id(self, upload_job_id):
        """Sets the upload_job_id of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param upload_job_id: The upload_job_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """

        self._upload_job_id = upload_job_id

    @property
    def upload_job_status(self):
        """Gets the upload_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The upload_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._upload_job_status

    @upload_job_status.setter
    def upload_job_status(self, upload_job_status):
        """Sets the upload_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param upload_job_status: The upload_job_status of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and upload_job_status is None:  # noqa: E501
            raise ValueError("Invalid value for `upload_job_status`, must not be `None`")  # noqa: E501
        allowed_values = ["waiting", "created", "started", "finished", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and upload_job_status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `upload_job_status` ({0}), must be one of {1}"  # noqa: E501
                .format(upload_job_status, allowed_values)
            )

        self._upload_job_status = upload_job_status

    @property
    def project_owner(self):
        """Gets the project_owner of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The project_owner of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._project_owner

    @project_owner.setter
    def project_owner(self, project_owner):
        """Sets the project_owner of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param project_owner: The project_owner of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """

        self._project_owner = project_owner

    @property
    def project_id(self):
        """Gets the project_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The project_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param project_id: The project_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def project_name(self):
        """Gets the project_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The project_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param project_name: The project_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def transformation_block_id(self):
        """Gets the transformation_block_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The transformation_block_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._transformation_block_id

    @transformation_block_id.setter
    def transformation_block_id(self, transformation_block_id):
        """Sets the transformation_block_id of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param transformation_block_id: The transformation_block_id of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """

        self._transformation_block_id = transformation_block_id

    @property
    def transformation_block_name(self):
        """Gets the transformation_block_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The transformation_block_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._transformation_block_name

    @transformation_block_name.setter
    def transformation_block_name(self, transformation_block_name):
        """Sets the transformation_block_name of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param transformation_block_name: The transformation_block_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """

        self._transformation_block_name = transformation_block_name

    @property
    def created(self):
        """Gets the created of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The created of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param created: The created of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and created is None:  # noqa: E501
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def output_dataset_name(self):
        """Gets the output_dataset_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The output_dataset_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._output_dataset_name

    @output_dataset_name.setter
    def output_dataset_name(self, output_dataset_name):
        """Sets the output_dataset_name of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param output_dataset_name: The output_dataset_name of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """

        self._output_dataset_name = output_dataset_name

    @property
    def total_download_file_count(self):
        """Gets the total_download_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The total_download_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._total_download_file_count

    @total_download_file_count.setter
    def total_download_file_count(self, total_download_file_count):
        """Sets the total_download_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param total_download_file_count: The total_download_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and total_download_file_count is None:  # noqa: E501
            raise ValueError("Invalid value for `total_download_file_count`, must not be `None`")  # noqa: E501

        self._total_download_file_count = total_download_file_count

    @property
    def total_download_file_size(self):
        """Gets the total_download_file_size of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The total_download_file_size of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._total_download_file_size

    @total_download_file_size.setter
    def total_download_file_size(self, total_download_file_size):
        """Sets the total_download_file_size of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param total_download_file_size: The total_download_file_size of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and total_download_file_size is None:  # noqa: E501
            raise ValueError("Invalid value for `total_download_file_size`, must not be `None`")  # noqa: E501

        self._total_download_file_size = total_download_file_size

    @property
    def total_download_file_size_string(self):
        """Gets the total_download_file_size_string of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The total_download_file_size_string of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: str
        """
        return self._total_download_file_size_string

    @total_download_file_size_string.setter
    def total_download_file_size_string(self, total_download_file_size_string):
        """Sets the total_download_file_size_string of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param total_download_file_size_string: The total_download_file_size_string of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and total_download_file_size_string is None:  # noqa: E501
            raise ValueError("Invalid value for `total_download_file_size_string`, must not be `None`")  # noqa: E501

        self._total_download_file_size_string = total_download_file_size_string

    @property
    def total_upload_file_count(self):
        """Gets the total_upload_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501


        :return: The total_upload_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :rtype: int
        """
        return self._total_upload_file_count

    @total_upload_file_count.setter
    def total_upload_file_count(self, total_upload_file_count):
        """Sets the total_upload_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.


        :param total_upload_file_count: The total_upload_file_count of this OrganizationGetCreateProjectsResponseAllOfJobs.  # noqa: E501
        :type: int
        """

        self._total_upload_file_count = total_upload_file_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationGetCreateProjectsResponseAllOfJobs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationGetCreateProjectsResponseAllOfJobs):
            return True

        return self.to_dict() != other.to_dict()
