
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-03T13:39:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2d7706ab3096803c98d1fc3111b6b4ba196b6a3",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
