[tool.poetry]
name = "invincible"
version = "0.0.1"
description = "Keep restarting process for ever"
authors = ["Hernan Ezequiel Di Giorgi <hernan.digiorgi@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
mypy = "^0.812"

[tool.poetry.scripts]
invincible = 'invincible:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
