
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T21:59:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "96c2c9ddbfe8b07662f3a98c1b2e0229b4597f1d",
 "version": "v1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
