
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T23:38:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc71076ac629b18197f037d5e062f451509480f5",
 "version": "0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
