
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T05:01:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f1988a2c69ec6bca05762978983dc90a91002c8",
 "version": "1.15.0.post.dev187"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
