[tool.poetry]
name = "api_schemas"
version = "0.1.4"
description = "Create an intermediate representation of an api schema, that can be used to generate code."
license = "MIT"
readme = "README.md"
authors = ["JulianSobott <julian.sobott@gmail.com>"]
repository = "https://github.com/JulianSobott/api_schemas"
homepage = "https://github.com/JulianSobott/api_schemas"
keywords = ["api", "schema", "code generation"]

[tool.poetry.dependencies]
python = "^3.9"
lark-parser = "^0.11.2"
Mako = "^1.1.4"
autopep8 = "^1.5.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
