[tool.poetry]
name = "muscad"
version = "0.5.1"
description = "OpenSCAD, with a Python Spice"
authors = ["Guillaume Pujol <guillp.linux@gmail.com>"]
readme = "README.rst"
repository = "https://gitlab.com/guillp/muscad"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
black = "^20.8b1"
pylint = "^2.7.4"
Sphinx = "^3.5.4"
mypy = "^0.812"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
