[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true

[tool.isort]
line_length = 120
profile = 'black'

[build-system]
requires = ['setuptools>=42', 'wheel', 'setuptools_scm[toml]>=3.4']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
