[tool.poetry]
name = "pyglslify"
version = "0.1.0"
description = "Thin wrapper for the glslify nodejs tool, use stack.gl shader modules in Python."
authors = ["Anentropic <ego@anentropic.com>"]
license = "MIT"
packages = [
    { include = "pyglslify.py" },
]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
ipython = "*"
ipdb = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
