
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T14:57:40+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5733e669c5f8b04d2480a03bdb5fc763306bb61",
 "version": "0.4.0-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
