#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='P_CombiningPValuesFinal',
      version='0.0.1',
      description='Functions within this module allow for multiple p values',
      author='Breya McGlown',
      author_email='bswlker2@memphis.edu',
      url='https://github.com/StatsGirl/Master2021',
      py_modules=['P_CombiningPValuesFinal'],
     )
