
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T11:06:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cce4cc8b1f161cbb53d09ab107b8000b20e757dc",
 "version": "2465"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
