[tool.poetry]
name = "gibihm"
version = "0.1.1"
description = "GitLab Issue Bot for Isochronal Heads-Up Monitoring"
authors = ["Dominik George <nik@naturalnet.de>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://edugit.org/nik/gibihm"
include = ["CHANGELOG.md"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.9"
python-gitlab = "^2.7.1"
dateparser = "^1.0.0"
croniter = "^1.0.12"
PyYAML = "^5.4.1"
click = "^7.1.2"
click-logging = "^1.0.1"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
gibihm = "gibihm.cli:gibihm"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
