# Generated by Django 3.2 on 2021-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid_connect_op', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openidclient',
            name='userinfo_in_id_token',
            field=models.BooleanField(default=False),
        ),
    ]
