[tool.semantic_release]
directory = '.'
version_variable = "setup.py:__version__"
branch = "master"
upload_to_pypi = false
upload_to_release = false
remove_dist = false
#dist_path = "dist/"
build_command = "python setup.py sdist bdist_wheel"
