[tool.poetry]
name = "mudkip"
version = "0.4.9"
description = "A friendly Sphinx wrapper"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/mudkip"
repository = "https://github.com/vberlier/mudkip"
documentation = "https://github.com/vberlier/mudkip"

readme = "README.md"

keywords = [
  "documentation",
  "sphinx",
  "jupyter-notebooks",
  "autodoc",
  "doctests"
]

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^3.5.3"
click = "^7.1.2"
watchdog = "^2.0.2"
sphinx-autodoc-typehints = "^1.11.1"
sphinx-rtd-theme = "^0.5.1"
livereload = "^2.6.3"
tomlkit = "^0.7.0"
notebook = "^6.3.0"
jupyter_nbextensions_configurator = "^0.4.1"
colorama = {version = "*", markers = 'sys_platform == "win32"'}
myst-parser = "^0.13.5"
myst-nb = "^0.12.0"
furo = "^2021.3.20-beta.31"

[tool.poetry.dev-dependencies]
black = { version = "^21.4b2", allow-prereleases = true }
python-semantic-release = "^7.15.4"

[tool.poetry.scripts]
mudkip = 'mudkip.cli:main'

[tool.semantic_release]
branch = "main"
version_variable = ["mudkip/__init__.py:__version__"]
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
build_command = "poetry build && poetry run mudkip build --check --update-gh-pages --repository https://x-access-token:${GH_TOKEN}@github.com/vberlier/mudkip"

[tool.mudkip]
preset = "furo"

[tool.mudkip.override]
html_title = "Mudkip"
suppress_warnings = ["myst.header"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
