[tool.poetry]
name = "neon_diagrams"
version = "0.1.0"
description = "Diagrams for Neon Law"
authors = ["neon law <support@neonlaw.com>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^21.4b2"
diagrams = "^0.19.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
