
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-06T00:54:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f39767fdf4f9d647c0b37491d57a6c839425a174",
 "version": "1.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
