# Generated by Django 2.2.15 on 2020-08-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=16, null=True)),
                ('lev', models.CharField(default='user', max_length=16)),
                ('status', models.CharField(max_length=16, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'firebase_user',
                'managed': True,
                'proxy': False,
            },
        ),

        migrations.RunSQL ("ALTER TABLE firebase_user ALTER COLUMN created_at SET DEFAULT now();"),
        migrations.RunSQL ("ALTER TABLE firebase_user ALTER COLUMN updated_at SET DEFAULT now();"),
        migrations.RunSQL ("ALTER TABLE firebase_user ALTER COLUMN lev SET DEFAULT 'user';"),
        migrations.RunSQL ("ALTER TABLE firebase_user ALTER COLUMN email_verified SET DEFAULT false;"),
    ]
