# Generated by Django 2.2.15 on 2020-08-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0002_auto_20200829_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='nick_name',
        ),
    ]
