# Generated by Django 2.2.15 on 2020-08-30 07:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0004_auto_20200830_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=16)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
                'db_table': 'firebase_user_log',
                'managed': True,
                'proxy': False,
            },
        ),
        migrations.RunSQL ("ALTER TABLE firebase_user_log ALTER COLUMN created SET DEFAULT now();"),
    ]
