[tool.poetry]
name = "awyes"
version = "0.1.0"
description = "Simplify your aws deployment"
authors = ["trumanpurnell <truman.purnell@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
