
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-03T10:28:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff2b0eb7f0e26d8608841c82c5b3b3a17ece581f",
 "version": "0.4.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
