[tool.poetry]
authors = ["duyixian <duyixian1234@qq.com>"]
description = "pip repository manager"
license = "MIT"
name = "prm"
version = "0.1.3"

[tool.poetry.dependencies]
click = "^7.1.2"
python = "^3.8"

[tool.poetry.scripts]
prm = "prm.prm:main"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
pylint = "^2.8.2"
pytest = "^6.2.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
