# Generated by Django 2.2.15 on 2020-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
