# Generated by Django 2.2.15 on 2020-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0007_auto_20200830_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
