[tool.poetry]
name = "agtest"
version = "0.1.1"
description = ""
authors = ["MrSuperbear <fraser.darrin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"
click = "^7.1.2"
arrow = "^0.17.0"
parse = "^1.17.0"
pandas = "^1.1.1"
regobj = "^0.2.2"
openpyxl = "^3.0.5"
pdf2image = "^1.14.0"
comtypes = "^1.1.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
agtest = "agtest.cli:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

