# Generated by Django 2.2.16 on 2020-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0010_auto_20200830_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
