
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T10:56:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4300f8178ac01eab3e1c89645916f44af563f630",
 "version": "2464"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
