from edc_auth.codenames import clinic_super

clinic_super += [
    "mocca_prn.delete_endofstudy",
    "mocca_prn.delete_losstofollowup",
    "mocca_prn.delete_offschedule",
    "mocca_prn.delete_onschedule",
    "mocca_prn.delete_protocoldeviationviolation",
    "mocca_subject.delete_bloodresultslipid",
    "mocca_subject.delete_cd4result",
    "mocca_subject.delete_clinicalreview",
    "mocca_subject.delete_clinicalreviewbaseline",
    "mocca_subject.delete_complicationsbaseline",
    "mocca_subject.delete_complicationsfollowup",
    "mocca_subject.delete_dminitialreview",
    "mocca_subject.delete_dmreview",
    "mocca_subject.delete_drugrefilldm",
    "mocca_subject.delete_drugrefillhiv",
    "mocca_subject.delete_drugrefillhtn",
    "mocca_subject.delete_drugrefillchol",
    "mocca_subject.delete_glucose",
    "mocca_subject.delete_glucosebaseline",
    "mocca_subject.delete_hivinitialreview",
    "mocca_subject.delete_hivreview",
    "mocca_subject.delete_htninitialreview",
    "mocca_subject.delete_cholinitialreview",
    "mocca_subject.delete_htnreview",
    "mocca_subject.delete_cholreview",
    "mocca_subject.delete_hivmedicationadherence",
    "mocca_subject.delete_dmmedicationadherence",
    "mocca_subject.delete_htnmedicationadherence",
    "mocca_subject.delete_cholmedicationadherence",
    "mocca_subject.delete_indicators",
    "mocca_subject.delete_medications",
    "mocca_subject.delete_nextappointment",
    "mocca_subject.delete_otherbaselinedata",
    "mocca_subject.delete_patienthealth",
    "mocca_subject.delete_subjectrequisition",
    "mocca_subject.delete_subjectvisit",
    "mocca_subject.delete_subjectvisitmissed",
    "mocca_subject.delete_viralloadresult",
]

clinic_super.sort()
