[tool.poetry]
name = "nlp-service"
version = "0.1.0"
description = "Microservice for NLP tasks using gRPC"
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/ReCAP-UTR/NLP"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.19.5"
scipy = "^1.6.2"
spacy = "^3.0.5"
grpcio = "^1.32"
arg-services = "^0.1.7"
tensorflow = { version = "^2.4.1", optional = true }
sentence-transformers = { version = "^1.0.4", optional = true }
tensorflow-hub = { version = "^0.11.0", optional = true }
gensim = { version = "^4.0.1", optional = true }
pyemd = { version = "^0.5.1", optional = true }
typer = { version = "^0.3.2", optional = true }
python-Levenshtein = { version = "^0.12.2", optional = true }
torch = { version = "^1.8.1", optional = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
server = [
    "sentence-transformers",
    "tensorflow",
    "tensorflow-hub",
    "gensim",
    "python-levenshtein",
    "typer",
    "pyemd",
    "torch",
]


# arg-services = "^0.1.6"
