
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-30T11:32:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "347ddaef6165f515c2aff94e6e14d4885ba4210b",
 "version": "0.8.5b0.dev202105010717"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
