
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-05T17:36:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c9022730d940cc57f87ce7a4da82f18b4c1f261",
 "version": "1.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
