[tool.poetry]
name = "tiff"
version = "0.0.5"
description = "GeoTiff utils package"
authors = ["Moleque <molecada@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "*"
rasterio = "*"
pyproj = "*"
pillow = "*"
geopy = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
