# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from edge_impulse_sdk.configuration import Configuration


class ProjectInfoResponseAllOfDeploySettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'eon_compiler': 'bool',
        'sensor': 'str'
    }

    attribute_map = {
        'eon_compiler': 'eonCompiler',
        'sensor': 'sensor'
    }

    def __init__(self, eon_compiler=None, sensor=None, local_vars_configuration=None):  # noqa: E501
        """ProjectInfoResponseAllOfDeploySettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._eon_compiler = None
        self._sensor = None
        self.discriminator = None

        self.eon_compiler = eon_compiler
        self.sensor = sensor

    @property
    def eon_compiler(self):
        """Gets the eon_compiler of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501


        :return: The eon_compiler of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501
        :rtype: bool
        """
        return self._eon_compiler

    @eon_compiler.setter
    def eon_compiler(self, eon_compiler):
        """Sets the eon_compiler of this ProjectInfoResponseAllOfDeploySettings.


        :param eon_compiler: The eon_compiler of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and eon_compiler is None:  # noqa: E501
            raise ValueError("Invalid value for `eon_compiler`, must not be `None`")  # noqa: E501

        self._eon_compiler = eon_compiler

    @property
    def sensor(self):
        """Gets the sensor of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501


        :return: The sensor of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501
        :rtype: str
        """
        return self._sensor

    @sensor.setter
    def sensor(self, sensor):
        """Sets the sensor of this ProjectInfoResponseAllOfDeploySettings.


        :param sensor: The sensor of this ProjectInfoResponseAllOfDeploySettings.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and sensor is None:  # noqa: E501
            raise ValueError("Invalid value for `sensor`, must not be `None`")  # noqa: E501
        allowed_values = ["accelerometer", "microphone", "camera", "unknown"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and sensor not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `sensor` ({0}), must be one of {1}"  # noqa: E501
                .format(sensor, allowed_values)
            )

        self._sensor = sensor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectInfoResponseAllOfDeploySettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectInfoResponseAllOfDeploySettings):
            return True

        return self.to_dict() != other.to_dict()
