# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from edge_impulse_sdk.configuration import Configuration


class SetProjectDspFileSizeRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dsp_file_size_mb': 'int'
    }

    attribute_map = {
        'dsp_file_size_mb': 'dspFileSizeMb'
    }

    def __init__(self, dsp_file_size_mb=None, local_vars_configuration=None):  # noqa: E501
        """SetProjectDspFileSizeRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dsp_file_size_mb = None
        self.discriminator = None

        self.dsp_file_size_mb = dsp_file_size_mb

    @property
    def dsp_file_size_mb(self):
        """Gets the dsp_file_size_mb of this SetProjectDspFileSizeRequest.  # noqa: E501

        DSP File size in MB (default is 4096 MB)  # noqa: E501

        :return: The dsp_file_size_mb of this SetProjectDspFileSizeRequest.  # noqa: E501
        :rtype: int
        """
        return self._dsp_file_size_mb

    @dsp_file_size_mb.setter
    def dsp_file_size_mb(self, dsp_file_size_mb):
        """Sets the dsp_file_size_mb of this SetProjectDspFileSizeRequest.

        DSP File size in MB (default is 4096 MB)  # noqa: E501

        :param dsp_file_size_mb: The dsp_file_size_mb of this SetProjectDspFileSizeRequest.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and dsp_file_size_mb is None:  # noqa: E501
            raise ValueError("Invalid value for `dsp_file_size_mb`, must not be `None`")  # noqa: E501

        self._dsp_file_size_mb = dsp_file_size_mb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetProjectDspFileSizeRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SetProjectDspFileSizeRequest):
            return True

        return self.to_dict() != other.to_dict()
