[tool.poetry]
name = "nqontrol"
version = "1.2.2-beta.0"
description = "Python program for digital control-loops."
authors = [
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
"Luis Dekant <ldekant@physnet.uni-hamburg.de>",
"Sebastian Steinlechner <sebastian.steinlechner@physnet.uni-hamburg.de>",
]
readme = "README.md"
repository = "https://gitlab.com/las-nq/nqontrol"
documentation = "https://las-nq-serv.physnet.uni-hamburg.de/python/nqontrol/"

[tool.poetry.scripts]
nqontrol = "nqontrol.gui.gunirun:main"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.14"
dash = "^1.11.0"
plotly = "^4.3"
pandas = "^1.0"
scipy = "^1.0"
openqlab = "^0.3.0"
ADwin = "^0.16.2"
matplotlib = "^3.2.1"
fastnumbers = "^3.0.0"
jsonpickle = "^1.4"
gunicorn = "^20.0.4"
Flask = "^1.1.2"
importlib-metadata = {version = "^1.6", python = "<=3.7"}
dash_daq = "^0.5.0"
websocket_client = "^0.57.0"

[tool.poetry.dev-dependencies]
Sphinx = "^3.0.1"
black = "^20.8b1"
nbconvert = "^6.0.7"
sphinx-markdown-tables = "^0.0.15"
sphinx-rtd-theme = "^0.5"
recommonmark = "^0.6.0"
jupyter-contrib-nbextensions = "^0.5.1"
pytest = "^6.1.2"
pytest-cov = "^2.8.1"
mypy = "^0.790"
pylint = "^2.4.4"
ipdb = "^0.13.2"
pydocstyle = "^5.0.2"
autopep8 = "^1.5.1"
pre-commit = "^2.2.0"
isort = "^5.6.4"
seed-isort-config = "^2.1.1"
rope = "^0.18.0"
websockets = "^8.1"
websocket_client = "^0.57.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
