[tool.poetry]
name = "lime-uow"
version = "0.1.45"
description = "Framework to support the Unit-of-Work pattern"
authors = ["Mark Stefanovic <markstefanovic@hotmail.com>"]
include = ["lime_uow/py.typed"]
license = "MIT"
repository = "https://github.com/MarkStefanovic/lime-uow"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
SQLAlchemy = { version = ">=1.3.19,<2.0", optional = true }
pyodbc = { version = ">=4.0.30,<5.0", optional = true }

[tool.poetry.extras]
pyodbc = ["pyodbc"]
sqlalchemy = ["SQLAlchemy"]

[tool.poetry.dev-dependencies]
pytest = ">=6.1.2,<7.0"
python-dotenv = ">=0.15.0,<1.0"
mypy = ">=0.79"
SQLAlchemy = "^1.4.12"
pyodbc = "^4.0.30"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
