
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-02T17:33:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "355ba45e41e069d9423f37c527cec71e4016b606",
 "version": "2.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
