[tool.poetry]
name = "woe-scoring"
version = "0.2.3"
description = "Weight Of Evidence Transformer and LogisticRegression model with scikit-learn API"
authors = ["Kirill Stroganov <kiraplenkin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
