[tool.poetry]
name = "kolore"
version = "0.1.14"
description = "Your tiny swiss-army knife for color palettes."
authors = ["AlvarBer <git@alvarber.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/AlvarBer/kolore"
keywords = ["colors", "palette", "krita", "image", "unity"]

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^8.1.0"
click = "^7.1.2"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kolore = "kolore.main:main"
