
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-29T18:24:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9244ae9689ac6f6db5969e3d07dded5ff8893b0",
 "version": "v0.17a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
