
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T12:39:42+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "32d8d585e4050244d6f418b8adf57d5661cd5861",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
