name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CPython 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install/fetch dependencies
        run: |
          set -exuo pipefail
          pip install --upgrade pip setuptools
          pip install tox

      - name: Run linter
        run: tox -e lint
