# Generated by Django 2.2.16 on 2020-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0012_auto_20200920_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lev',
            field=models.CharField(choices=[('guest', 'guest'), ('user', 'user'), ('staff', 'staff')], default='user', max_length=16),
        ),
    ]
