
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T03:44:42+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b577dfe5c4ebdc5256b40ad7ab7123cb913cf75d",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
