
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-30T10:28:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a59a99b54bdec5c0caf0d148fd57fede788e8205",
 "version": "v2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
