
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T20:29:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0288e6a59a4b82ab858bdbf6ba61a08e1cf0f9e7",
 "version": "0.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
