# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.create_user_third_party_response_all_of import CreateUserThirdPartyResponseAllOf  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestCreateUserThirdPartyResponseAllOf(unittest.TestCase):
    """CreateUserThirdPartyResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserThirdPartyResponseAllOf(self):
        """Test CreateUserThirdPartyResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.create_user_third_party_response_all_of.CreateUserThirdPartyResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
