# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.count_samples_response import CountSamplesResponse  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestCountSamplesResponse(unittest.TestCase):
    """CountSamplesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountSamplesResponse(self):
        """Test CountSamplesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.count_samples_response.CountSamplesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
