# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.api.admin_api import AdminApi  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = edge_impulse_sdk.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_add_user_to_project(self):
        """Test case for admin_add_user_to_project

        Add current user to a project  # noqa: E501
        """
        pass

    def test_admin_find_user(self):
        """Test case for admin_find_user

        Find a user  # noqa: E501
        """
        pass

    def test_admin_get_user(self):
        """Test case for admin_get_user

        Get user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
