# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.api.optimization_api import OptimizationApi  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestOptimizationApi(unittest.TestCase):
    """OptimizationApi unit test stubs"""

    def setUp(self):
        self.api = edge_impulse_sdk.api.optimization_api.OptimizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_trial(self):
        """Test case for create_trial

        Create trial  # noqa: E501
        """
        pass

    def test_get_state(self):
        """Test case for get_state

        Retrieves the EON tuner state  # noqa: E501
        """
        pass

    def test_update_config(self):
        """Test case for update_config

        Update config  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
