# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.dsp_metadata_output_config_shape import DSPMetadataOutputConfigShape  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestDSPMetadataOutputConfigShape(unittest.TestCase):
    """DSPMetadataOutputConfigShape unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDSPMetadataOutputConfigShape(self):
        """Test DSPMetadataOutputConfigShape"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.dsp_metadata_output_config_shape.DSPMetadataOutputConfigShape()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
