# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.track_objects_response_all_of import TrackObjectsResponseAllOf  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestTrackObjectsResponseAllOf(unittest.TestCase):
    """TrackObjectsResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackObjectsResponseAllOf(self):
        """Test TrackObjectsResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.track_objects_response_all_of.TrackObjectsResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
