# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.list_portal_files_in_folder_response_all_of import ListPortalFilesInFolderResponseAllOf  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestListPortalFilesInFolderResponseAllOf(unittest.TestCase):
    """ListPortalFilesInFolderResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPortalFilesInFolderResponseAllOf(self):
        """Test ListPortalFilesInFolderResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.list_portal_files_in_folder_response_all_of.ListPortalFilesInFolderResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
