[tool.poetry]
name = "rrm"
version = "0.1.0"
license = "MIT"
description = "Really, relentlessly and repeatedly remove files and all of their copies."
authors = ["Steffen Brinkmann <s-b@mailbox.org>"]
readme = "README.rst"
repository = "https://gitlab.com/szs/rrm/"
keywords = ["terminal", "console", "command line", "system tool", "cli"]
classifiers = ["Development Status :: 4 - Beta",
            "Environment :: Console",
            "Intended Audience :: System Administrators",
            "License :: OSI Approved :: MIT License",
            "Topic :: System",
            "Topic :: Utilities",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Programming Language :: Python :: 3.9",
]


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
