[tool.poetry]
name = "fixtopt-xtofl"
version = "0.1.3-beta"
description = "Pytest extension for adding test options"
authors = ["xtofl <xtofl@fixtopt.com>"]
license = "MIT"
packages = [
    { include = "fixtopt", from = "src" }
]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Testing",
    "Operating System :: OS Independent",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
