# Generated by Django 3.2 on 2021-05-04 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('task_file', models.FileField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterJobs',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=25)),
                ('scheduled_hour', models.PositiveIntegerField(null=True)),
                ('scheduled_min', models.PositiveIntegerField(null=True)),
                ('scheduled_date', models.DateField(null=True)),
                ('periodic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_executed', 'NOT_EXCECUTED'), ('pending', 'PENDING'), ('executed', 'EXECUTED'), ('killed', 'KILLED')], default='not_executed', max_length=25)),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_jobs', to='schedule_jobs.registertask')),
            ],
        ),
    ]
