# Generated by Django 3.2 on 2021-05-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertask',
            name='task_file',
            field=models.FileField(null=True, upload_to='../'),
        ),
    ]
