# Generated by Django 2.2.15 on 2020-08-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0003_auto_20200830_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
