# Generated by Django 2.2.15 on 2020-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0005_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
