# Generated by Django 2.2.15 on 2020-08-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0008_auto_20200830_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.TextField(null=True),
        ),
    ]
