# Generated by Django 2.2.16 on 2020-09-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0011_auto_20200914_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
