[tool.poetry]
name = "split-schedule"
version = "0.3.4"
description = "Split schedule into smaller class sizes"
authors = ["Paul Sanders <psanders1@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sanders41/split-schedule"
homepage = "https://github.com/sanders41/split-schedule"
documentation = "https://github.com/sanders41/split-schedule"
keywords = ["schools", "schedule"]
classifiers=[
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
include = ["split_schedule/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.2"
openpyxl = "^3.0.5"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
flake8 = "^3.9.1"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.12.1"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
tox = "^3.23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)/
'''

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["split_schedule", "tests"]
