
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-04T10:25:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9256ca66a7afde92751b29b0fcc4a4e5343f11ea",
 "version": "2463"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
