
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-06T05:19:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cd291ca57a82b4b1c2e86c2859af24ab77db19e",
 "version": "0.7.0.post.dev92"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
